### ISSUE TITLE
Compatibility to JDK 8 and JDK 9 at the same time? 

### ISSUE THREAD

**Issue by cnsgithub** [jboss-javassist/javassist#171]
Hi, is the next version supposed to support JDK9 and JDK8? I'm currently experiencing this exception when running the master on JDK8. Or is there a 'special' way i need to build the jar? 

```java
Caused by: java.lang.NoClassDefFoundError: java/lang/StackWalker$Option
	at javassist.util.proxy.DefineClassHelper$SecuredPrivileged$1.<init>(DefineClassHelper.java:67)
	at javassist.util.proxy.DefineClassHelper$SecuredPrivileged.<clinit>(DefineClassHelper.java:38)
	at javassist.util.proxy.DefineClassHelper.<clinit>(DefineClassHelper.java:177)
	at javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:128)
	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:552)
	at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:537)
	at javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:473)
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:444)
	at org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.postInstantiate(JavassistProxyFactory.java:75)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:162)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:163)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:58)
	... 131 more
Caused by: java.lang.ClassNotFoundException: java.lang.StackWalker$Option
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jboss.modules.JDKSpecific.getSystemClass(JDKSpecific.java:183)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:397)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 143 more
```

P.S Would it be possible to get a build of the 'master' somewhere? So i don't have to build it? Unfortunately the latest GA release causes a NPE (which has been fixed in a later commit)

**Comment by nickl-** [comment]
> Hi, is the next version supposed to support JDK9 and JDK8? I'm currently experiencing this exception when running the master on JDK8. Or is there a 'special' way i need to build the jar?

Currently the tests require java 9 and I have not tested a build with 1.8 so have no idea. 

I know we are building **source=1.6** so the idea is to be able to run the compiled sources against even a 1.6 vm, this is also not tested yet.

> Would it be possible to get a build of the 'master' somewhere? So i don't have to build it? Unfortunately the latest GA release causes a NPE (which has been fixed in a later commit)

As far as I know, at the time of this writing, the latest release is 3.22.0-GA (October 10th) but the repository does include a file javassist.jar in the root of the project which was last build November 15th and should include everything committed up to and including this date.

Please let us know what find...

**Comment by mads1980** [comment]
I can confirm that 3.22.0 does not work in Java 8 since StackWalker is not present and we get a NoClassDefFoundError

Seems we need to stick to 3.21.0 in Java 8 until this is resolved.

**Comment by nickl-** [comment]
This is designated `JAVA_9` not sure why JDK8 would try and interpret the `StackWalker`. 

https://github.com/jboss-javassist/javassist/blob/c4e194994f5d07cab64b54754fcee884d9287949/src/main/javassist/util/proxy/DefineClassHelper.java#L38-L67

**Comment by beikov** [comment]
I just ran into the same issue. I wanted to update to 3.23.0 to test with JDK 11, but when running on JDK 8 with that version, I also get this error.

**Comment by arungitan** [comment]
just to confirm - if we have a requirement to run on both java8 and java11 (our code is compiled on java8), should we use v23 or wait for next version?

**Comment by johnou** [comment]
@arungitan wait for next version, see https://github.com/jboss-javassist/javassist/pull/204#issuecomment-400141378
